### ISSUE TITLE
Intelij: 2024.2 Investigation of Test Automation Changes in the Action Menu After Migration to Gradle IntelliJ Plugin 2.* and Modifications in runIdeForUiTests

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#1018]
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1066 - Staicy - In Progress
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1067 - Vaisakh - Closed

I noticed a change in the `Action Menu` bar after migrating to the Gradle IntelliJ Plugin `2.*` and modifying the `runIdeForUiTests`. 

A screenshot of the Action Menu bar after these changes is shown below,

<img width="1390" alt="Screenshot 2024-10-15 at 12 43 06 PM" src="https://github.com/user-attachments/assets/1f458451-98e1-439f-a27a-672ee67427be">

Screenshot of the Action Menu bar based on the current main code UI test.

<img width="1389" alt="Screenshot 2024-10-15 at 12 14 56 PM" src="https://github.com/user-attachments/assets/ee32b171-5280-45a2-b306-ae6a1f8d244d">

**Comment by vaisakhkannan** [comment]
As part of the investigation, I had a chat in the JetBrains Slack channel. Here is the link https://jetbrains-platform.slack.com/archives/C026SVA9MMM/p1729077907382179

As mentioned in the Slack channel, the classic UI has been removed starting from version 2024.2. Users who need the classic UI in `2024.2` will need to install a separate plugin called [Classic UI](https://plugins.jetbrains.com/plugin/24468-classic-ui/versions).

**Comment by TrevCraw** [comment]
Thank you @vaisakhkannan. My initial thoughts are that we should not let test automation dictate our support in production. Just because we move to a new UI for the test automation does not mean we cannot support the old UI with our plugin.

Regarding Java versions, as long as we are not using Java 21 features, we may be able to build against Java 21 and run on Java 17. Or, if that is not best practice, it may be possible to build with Java 17 and run on Java 21. I will defer to @mrglavas for the best way to achieve multiple levels of JVM support.

Regardless of the strategy, we will need to test it out. We should be able to find a way to support both 2024.1 and 2024.2. According to the JetBrains marketplace, Quarkus Tools supports both 2024.1 and 2024.2 - https://plugins.jetbrains.com/plugin/13234-quarkus-tools/versions. I do not see Quarkus Tools using Java 21 in their build file - https://github.com/redhat-developer/intellij-quarkus/blob/main/build.gradle.kts#L133-L139. I would recommend trying out Quarkus Tools on 2024.2.

Maybe you can find other example plugins that support 2024.1 and 2024.2 and see how they do it?

**Comment by TrevCraw** [comment]
Let's keep this issue about discussions related to test automation and move the Java support discussion over to https://github.com/OpenLiberty/liberty-tools-intellij/issues/1019. FYI @mrglavas.

**Comment by vaisakhkannan** [comment]
There is one behavioral difference between Windows and Mac in the new UI for supporting IntelliJ 2024.2

Windows bebaviour

https://github.com/user-attachments/assets/cac82826-acb8-4d1b-815c-1f8837dce12b

Mac behaviour

https://github.com/user-attachments/assets/7f0191df-1d62-4ed1-9940-2780788bd7ae


"I think we should check the conditions to determine which OS is running the UI test. Based on that, we should execute the tests. I also need to check the UI changes on Linux.

**Comment by turkeylurkey** [comment]
If we're doing File > Save All does this matter?

**Comment by vaisakhkannan** [comment]
> If we're doing File > Save All does this matter?

@turkeylurkey , Do you mean a double shift action?

<img width="739" alt="Screenshot 2024-10-28 at 8 28 07 PM" src="https://github.com/user-attachments/assets/5d8fea76-7398-4472-8e04-377d72599b44">

**Comment by vaisakhkannan** [comment]
I checked the UI behavior on `Linux` today, and the behavior is the same as on Windows, so we can use the same common code for both Windows and Linux
