### ISSUE TITLE
intellij 2024.2: Check plugin info and change notes are displayed properly in marketplace

### ISSUE THREAD

**Issue by staicy123** [OpenLiberty/liberty-tools-intellij#1112]
We need to confirm that the plugin information and change notes are displayed correctly in the JetBrains Marketplace. To do this, we should upload an early version of the plugin to a private repository or stream in the JetBrains Marketplace.

Acceptance Criteria:
Upload an early version of the plugin to a private repo/stream in the JetBrains Marketplace.
Verify that plugin details, including information and change notes

**Comment by staicy123** [comment]
Hi @TrevCraw,
I’m unsure about how to upload an early version of the plugin to a private repository or stream it in the JetBrains Marketplace. Could you please provide guidance on this?

Regarding plugin details verification, including information and change notes, I’ve already performed that locally. I generated the plugin ZIP by building it with our IntelliJ 2024.2 support changes, installed the generated plugin into IntelliJ, and verified that the correct change notes were displayed based on the new changes.

To test this locally, I modified the Liberty version in the change notes to 24.0.10, generated the ZIP, and manually installed it. I was able to confirm that the changes were reflected as expected.

<img width="1281" alt="Screenshot 2024-11-15 at 12 40 20 PM" src="https://github.com/user-attachments/assets/1a051de7-a7b2-4f0b-b670-401b81db81f1">

Thanks,

**Comment by mrglavas** [comment]
> Hi @TrevCraw, I’m unsure about how to upload an early version of the plugin to a private repository or stream it in the JetBrains Marketplace. Could you please provide guidance on this?

@staicy123 You might find this documentation helpful on creating custom plugin repositories: https://plugins.jetbrains.com/docs/intellij/custom-plugin-repository.html#format-of-updatepluginsxml-file

**Comment by mrglavas** [comment]
I built the [intellij-2024.2-support-backup](https://github.com/OpenLiberty/liberty-tools-intellij/tree/intellij-2024.2-support-backup) feature branch this morning and completed a test upload to the JetBrains Marketplace.

It was able to display information on the plug-in:
![image](https://github.com/user-attachments/assets/8fde6286-6cdb-42fc-bc80-3f70fd83debf)

It was also able to display the change notes:
![image](https://github.com/user-attachments/assets/044c92c7-f366-4c88-9462-1d259dd06630)

Since this all appears to be working, I am closing this issue.
