### ISSUE TITLE
Deliver an error/warning message if Java 17 is not found to launch language servers

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#196]
We should try and launch the language servers with Java 17. If possible, deliver a helpful error/warning message if Java 17 is not found

Right now we are using java.home 
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java#L37

which should resolve to the IntelliJ boot JDK: https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by TrevCraw** [comment]
In the error message, we can refer users to the link for switching the boot JDK and instruct them to select a Java 17 JDK.
https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by TrevCraw** [comment]
The Java version error message should be set up in  https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/resources/messages/LibertyBundles.properties and should be displayed to the user through an error window popup. 

The Java home error message should also be surfaced to the user

**Comment by angelozerr** [comment]
IMHO I think that server definition should provide info about the runtime which starts the ls like java runtime minimal version, nodejs runtime version etc

Once this info is declared the language server UI settings can provide a combo with the proper runtime and validate the selected runtime to start the ls. In other words we can see error of the java runtime version in the UI settings. IJ quarkus already provide the settings of the language server like debug port. We plan to support runtime in https://github.com/redhat-developer/intellij-quarkus/issues/1047

When the ls will syart with the wrong runtime it will report error in the lsp console and will disable the ls.

**Comment by TrevCraw** [comment]
@angelozerr thanks for sharing, we will add an enhancement issue for this

**Comment by TrevCraw** [comment]
@anusreelakshmi934 just wanted to note what was discussed at scrum plus some extra things I discussed with @mrglavas later in the day:

The goal for this issue is to provide 3 separate `java.home` checks and error messages for each language server that is launched (the 4 language servers being Liberty, LemMinX, Eclipse LSP4Jakarta and Eclipse LSP4MP).
- one check and error message for ensuring the `java.home` property exists: https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java#L39
- one check and error message for ensuring that the `java.home` property is a directory that exists
- one check and error message for ensuring that the `java.home` property points to Java 17 or higher: https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java#L43

All 3 error messages should be surfaced to the user and sent to the logger.

All 3 error messages should be defined in https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/resources/messages/LibertyBundles.properties

Instead of repeating code in each of the 4 language server classes, it would be best to add a single method (something like `checkJavaHome()`) to the parent class that each language server class extends: https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/server/ProcessStreamConnectionProvider.java#L13

The only difference to consider between each of the language servers is the name. There will need to be a parameter to fill in the name for each of the 3 error messages defined in https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/resources/messages/LibertyBundles.properties. There also needs to be a parameter for the name for the common method defined in the ProcessStreamConnectionProvider class (or an abstract method would need to be defined like `getName()`, which each of the four language server classes would implement by returning their name).
