### ISSUE TITLE
Enhancement for race condition in inspections and diagnostics logic 

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#278]
Consider a potential performance enhancement to address the race condition between the [LSPLocalInspectionTool#checkFile()](https://github.com/OpenLiberty/liberty-tools-intellij/blob/54632ee3d31edebeeeb8a2d722471593a66592bf/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPLocalInspectionTool.java#L64) and [LSPDiagnosticsToMarkers#accept()](https://github.com/OpenLiberty/liberty-tools-intellij/blob/54632ee3d31edebeeeb8a2d722471593a66592bf/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/diagnostics/LSPDiagnosticsToMarkers.java#L55) logic. 

See more details here https://github.com/OpenLiberty/liberty-tools-intellij/pull/277#pullrequestreview-1318754519

**Comment by evie-lau** [comment]
Now using ExternalAnnotator in favor over LSPLocalInspectionTool. 
There was still a race condition using the ExternalAnnotator, which was fixed by #307.

There may be a complete diagnostics rewrite soon in the intellij-quarkus project, which has similar logic rearrangement to the fix mentioned above.
