### ISSUE TITLE
Remove liberty project dialog message shows a null project

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#321]
Sequence of events:
- Ran search everywhere action:  `Liberty: Add project to the tool window`. The project was successfully added to the Liberty tool window.
- Ran search everywhere action: `Liberty: Remove project from the tool window`. The dialog titled `Remove Liberty project` asking the user if the project should be deleted shows a null (project name) in the message.  

Liberty: Add project to the tool window
<img width="867" alt="image" src="https://user-images.githubusercontent.com/8353153/229220797-1ae264ac-c7c6-4ba0-a32b-265d8c6fabbe.png">

**Comment by TrevCraw** [comment]
Just noting the variable that is null.

![projectName-null](https://user-images.githubusercontent.com/5885743/232166071-fef0458b-06f2-442a-b3ca-377f15e2a604.png)

**Comment by TrevCraw** [comment]
This may be resolved by the fix for https://github.com/OpenLiberty/liberty-tools-intellij/issues/272

**Comment by TrevCraw** [comment]
With the changes in https://github.com/OpenLiberty/liberty-tools-intellij/pull/408, this bug is slightly changed. Instead of null, we get the root project/folder name. So for the https://github.com/openliberty/guide-reactive-rest-client project, if a user tries to remove the `inventory` project from the LT window, the following is displayed:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/5885743/75207cff-b3f9-45f9-b2a1-823ccf3cec5f)
