### ISSUE TITLE
Annotation appears twice in quick fix

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#362]
In test case JsonbTransientDiagnostic on line 31 there is a quick fix to remove the annotations "@JsonbAnnotation, @JsonbTransient" but the title of the quick fix is "Remove @JsonbTransient, @JsonbTransient, @JsonbAnnotation, @JsonbAnnotation" 

![image](https://user-images.githubusercontent.com/24705144/233461103-f3fba60f-762c-465f-a0f5-2e26d21cafc4.png)

This is because the annotation name resolution is finding jakarta.json.bind.annotation.JsonbTransient and also the javax equivalent. The resolution search scope is global, maybe limiting the scope to this file would fix it.

Note this was seen on Windows but not Mac.

**Comment by dshimo** [comment]
Was unable to reproduce on Mac and Linux.

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/8934136/9c44aac2-072c-4ac5-88da-4a561ee67ea4)

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/8934136/ab2a3128-f6ef-42d9-9b11-2a600a2899b7)

**Comment by anusreelakshmi934** [comment]
Tested using latest version of LSP4IJ. Quick Fix is not present
<img width="1136" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/141303561/0eac95f8-a5da-4abb-8d0e-46d654d56483">

**Comment by mrglavas** [comment]
I believe in order to reproduce the problem your environment would need to have both Java EE (`javax.*`) and Jakarta EE (`jakarta.*`). I'm pretty sure there was code which tried to convert a short name back to a qualified name and it was finding both sets of qualified names from Java EE and Jakarta EE. The solution was to consistently process qualified names across all of the diagnostic collectors and quick fixes to eliminate the conversion step.

**Comment by anusreelakshmi934** [comment]
<img width="784" alt="image" src="https://github.com/user-attachments/assets/aa1c603d-1b23-4568-8091-b7cf98ff59b1">

The issue is resolved on testing with using the latest lsp4ij feature branch (version - 0.0.2).

**Comment by turkeylurkey** [comment]
I also applied the fix for #703 locally and tested this. It is resolved.
