### ISSUE TITLE
Integrate newest LSP4Jakarta release when available

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#521]
The upcoming release for LSP4Jakarta may require code changes to integrate the language server with the language client.

When the newest release of LSP4Jakarta becomes available, update all references to latest version in preparation for next release.

There is one dependency that needs updating:
- org.eclipse.lsp4jakarta.ls-0.1.1-jar-with-dependencies.jar

Only one file should be affected:
- build.gradle (`implementation` and `lsp` lines)

Test to confirm no regression is introduced.

**Comment by mrglavas** [comment]
The release of LSP4Jakarta that is referred to by this issue is version 0.2.0: https://github.com/eclipse/lsp4jakarta/releases/tag/0.2.0. LSP4Jakarta 0.2.0 has refactored its client API to better align with the design of LSP4MP. Moving to this new level will allow us to wire the client for deferred resolution of code actions and will align completion messages with LSP4MP, allowing us to unify the design for completion for MP / Jakarta EE.

**Comment by mrglavas** [comment]
Code was merged into the LSP4iJ feature branch.
