### ISSUE TITLE
Investigate whether the properties file update bug has been fixed

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#606]
There was a problem to display a diagnostic after a properties file is update as reported in https://github.com/OpenLiberty/liberty-tools-intellij/issues/328

After updating lsp4ij and lsp4mp4ij we need to investigate whether the fix to that issue is still needed.

Related to https://github.com/OpenLiberty/liberty-tools-intellij/issues/592

**Comment by turkeylurkey** [comment]
Behaviour in VS Code: 
1. change the property in microprofile-config.properties to injected.value2 and it is live updated in the editor with a diagnostic that injected.value2 is not used in any Java file. Messages sent to lsp4mp.
2. View ConfigTestController.java which is already opened. No diagnostic. Change the file (messages sent to lsp4mp) and nothing happens on screen until you Save. Then a diagnostic appears that injected.value is not assigned a value in any config file.

**Comment by turkeylurkey** [comment]
Made a fix to LanguageServerWrapper.java in lsp4ij on branch q1201 commit fb4313302. This fix sets up data using the DocumentContentSynchronizer.KEY. It seems this fix is still needed on IntelliJ.

**Comment by turkeylurkey** [comment]
Initial keys in the microprofile-config.properties file:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/96620860-c916-4cb2-9c88-aaf53676dab1)
Add one character to the first key:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/4d59c29d-1f6e-43f5-9fde-5286cac2900c)
Key press is registered, new properties are read in:
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/ee69aca6-a21b-4e8d-90dc-a465d1712568)
First property has not been updated in the file.

**Comment by angelozerr** [comment]
We had the similar problem in ij quarkus that we have fixed a long time.

So I suggest that you mimic our code since your code was a copied pasted feom ij quarkus.

If I remember the problem is that when you type something iin properties files it doesnt update the cache. You need to save the file if I remember. But it is not enough because the cache uses not the propertieq file from src but from target folder which requires a compilation of the project.

We did that for jdt and it works well , but in ij when you save propzrties file it doesnt do compilation.

In otherwords in ij you need to change the strategy. The cache must be evicted when the psifile changed

**Comment by turkeylurkey** [comment]
Thank you, @angelozerr , it seemed like something you would have run into. Does the `microprofile/propertiesChanged` message drive the lsp4mp to send the Java diagnostic?

**Comment by angelozerr** [comment]
Yes, see https://github.com/eclipse/lsp4mp/blob/b5d02a1258acf63d8b2d80381ad9a987a3ce7478/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaFileTextDocumentService.java#L398

**Comment by turkeylurkey** [comment]
Enabled the `microprofile/propertiesChanged` message in commit 0e7941658044f on the branch useLSP4IJ1201. Needed to instantiate the listener in the xml.
