### ISSUE TITLE
Enable automated UI tests for language server capabilities on Windows.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#655]
Automated testing of the language servers is currently limited to Mac and Linux only. Revisit why the tests (annotated with `@DisabledOnOs({OS.WINDOWS})`) are not run on Windows and explore if there's a path forward for automation on Windows. See https://github.com/OpenLiberty/liberty-tools-intellij/issues/642 for discussion about these tests.

**Comment by TrevCraw** [comment]
possible duplicate: https://github.com/OpenLiberty/liberty-tools-intellij/issues/494

**Comment by anusreelakshmi934** [comment]
After removing the @DisabledOnOs({OS.WINDOWS}) annotation, I ran the tests as a cron job in my repo. 
Can see the builds that ran [here](https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/workflows/build.yaml?query=branch%3Amain+event%3Aschedule) 
Out of 31 jobs that ran till now, 22 of the windows builds were getting success in the first attempt.

2 of them got success when ran a second time .
`testCustomStartParametersClearedOnConfigRemoval()` in one build and both `testRunTestsActionUsingPopUpMenu()` and `testCustomStartParametersClearedOnConfigRemoval()` in another build were failing due to 

> org.opentest4j.AssertionFailedError: testCustomStartParametersClearedOnConfigRemoval:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.

and
>  org.opentest4j.AssertionFailedError: testRunTestsActionUsingPopUpMenu:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I in log:D:\a\liberty-tools-intellij\liberty-tools-intellij\liberty-tools-intellij\src\test\resources\projects\gradle\singleModGradleMP\build\wlp\usr\servers\defaultServer\logs\messages.log
 errors.

After re running almost all of them is getting success ( re running 2 or 3 times). Mostly the files was encountering Timed out error.
The error that frequently occurred in the builds is as follows:

> GradleSingleModJakartaLSTest > testInsertJakartaCodeSnippetIntoJavaPart() FAILED
>     java.util.NoSuchElementException: List is empty.
>     

Also same class failed once due to another error :
>  com.intellij.remoterobot.client.IdeaSideException
>  Caused by:
>         java.lang.Throwable: component must be showing on the screen to determine its location


Also sometimes some of the linux builds are also failing due to the following reasons. Mostly Timeout errors.Adding few of them below:

> testCustomStartParametersClearedOnConfigRemoval() FAILED
>     org.opentest4j.AssertionFailedError: testCustomStartParametersClearedOnConfigRemoval:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.
   
>  testStartWithConfigInDebugModeUsingToolbar() FAILED
>     com.intellij.remoterobot.client.IdeaSideException: Wrapped java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location

> testRunTestsActionUsingDropDownMenu() FAILED
>     org.opentest4j.AssertionFailedError: testRunTestsActionUsingDropDownMenu:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.

>  testStartWithConfigInDebugModeUsingMenu() FAILED
>     org.opentest4j.AssertionFailedError: testStartWithConfigInDebugModeUsingMenu:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I in log:/home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log

> GradleSingleModJakartaLSTest > initializationError FAILED
>     java.lang.RuntimeException: Unable to open file SystemResource
>         at io.openliberty.tools.intellij.it.UIBotTestUtils.openFile(UIBotTestUtils.java:645)
>         at io.openliberty.tools.intellij.it.SingleModJakartaLSTestCommon.prepareEnv(SingleModJakartaLSTestCommon.java:194)
>         at io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest.setup(GradleSingleModJakartaLSTest.java:43)
>         Caused by:
>         java.util.NoSuchElementException: List is empty.

I guess the above  initializationError FAILED error occured because the remoterobot was not able to find the SystemResource to open.Maybe it needed a bit delay there for the file to load.

**Comment by TrevCraw** [comment]
Hi @anusreelakshmi934 , please add your observations to https://github.com/OpenLiberty/liberty-tools-intellij/issues/494. Then please open an issue for each type of failure observed and add it as a work item to the 494 Epic.
