### ISSUE TITLE
Message is missing for RemoveModifierConflictQuickFix quick fix

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#703]
Using 24.0.3 release candidate in a smoke test I see that one of the quick fixes is displayed with the default tag rather than the message retrieved from the Messages file.
<img width="495" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/0d85fd7c-efd2-4b33-a7d5-39c9f19a7239">
The message is retrieved in RemoveModifierConflictQuickFix.

**Comment by TrevCraw** [comment]
This bug is not observed at this commit: https://github.com/OpenLiberty/liberty-tools-intellij/commit/1bf70bf9d679f65c88d8779d0797b6a7a9166d8d

**Comment by TrevCraw** [comment]
As part of this issue, we should consider what testing we would need to catch a bug like this.

**Comment by aparnamichael** [comment]
While testing LS features, I have seen the same issue with few other quick fixes as well.
LTI version used: 24.0.6 and build file generated from 'lsp4ij-market-0.0.2-integration' branch (part of 24.0.7 release)
IntelliJ version used: 2024.1.1

```
public static String getMessage(String key, Object... args) {
    if (resourceBundle == null) {
        initializeBundles();
    }
    String msg = null;
    try {
        msg = resourceBundle.getString(key);
        if (msg != null && args != null && args.length > 0) {
            msg = MessageFormat.format(msg, args);
        }
    } catch (Exception e) {
        LOGGER.debug("Failed to get message for '" + key + "'", e);
    }
    return (msg == null) ? key : msg;
}
```

This is the method we are using to get the value. When trying to get value from Message.properties it is throwing an exception "java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key RemoveItem" eventhough that key is present in Message.properties.

**Comment by aparnamichael** [comment]
List of quick fixes having this issue:

1. RemoveAnnotationConflictQuickFix
RemoveItem = Remove {0}

2. InsertAnnotationAttributesQuickFix
AddAtoB = Add {0} to {1}

3.  ManagedBeanNoArgConstructorQuickFix
AddProtectedConstructor = Add a no-arg protected constructor to this class
AddPublicConstructor = Add a no-arg public constructor to this class

4.  RemoveModifierConflictQuickFix
RemoveTheModifierFromThisField = Remove the ''{0}'' modifier from this field
RemoveTheModifierFromThisMethod = Remove the ''{0}'' modifier from this method
RemoveTheModifierFromThisClass = Remove the ''{0}'' modifier from this class

5. NoResourcePublicConstructorQuickFix
NoargPublicConstructor = Add a default 'public' constructor to this class

6.  PersistenceAnnotationQuickFix
AddTheMissingAttributes = Add the missing attributes to the @MapKeyJoinColumn annotation

7. CompleteFilterAnnotationQuickFix
RemoveTheAttributeFrom = Remove the `{0}` attribute from {1}

8. InsertAnnotationMissingQuickFix
InsertItem = Insert {0}

**Comment by mrglavas** [comment]
It's probably not a coincidence that these changes to LSP4Jakarta: https://github.com/eclipse/lsp4jakarta/commit/c0bd9b37777815dffd9c91567162d447baa30ef1#diff-af96c34f311ff93103a3aa8ef4bee8cfb4b65d098838e09b6bbb7f08a90d5e3f happen to have removed the keys that are now missing at runtime. When the messages.properties file was included in LTI, it was given the exact same path (`org.eclipse.lsp4jakarta.jdt.core.messages`) as in LSPJakarta, meaning that there are two resources with identical paths in the LTI plugin. With this ambiguity it's all up to luck on which gets loaded by the ClassLoader and I'm betting it's find the one from LSP4Jakarta instead of the local one from LTI. Giving the local file in LTI a unique path would resolve such an issue.

**Comment by mrglavas** [comment]
@TrevCraw Given that the root cause of this problem was a file conflict, I consider that to be a packaging error and would imagine we'd need to start checking the built plugin for the existence of conflicting class and resource files in LTI's dependencies. A direct functional test may never have (or at least not reliably) caught this because we might have been _unlucky_ and always ran the test in environment which happens to load the local file from LTI instead of the one from LSP4Jakarta.
