### ISSUE TITLE
Send LSP4IJ integration build results to Slack channel

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#759]
At the conclusion of each LSP4IJ integration build, a notification should be sent to Slack with the build status and a link to the build results and associated PR/branch.

Box note link for the Steps for adding secret : https://ibm.ent.box.com/notes/1552644894634

**Comment by Rahul-Biju** [comment]
Output:

When the build results are completed, we'll now receive notifications via Slack. The notification includes both Build results and status updates.

<img width="1084" alt="Screenshot 2024-06-04 at 6 55 52 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133862121/bfa80063-f49e-4c15-a9b3-58ff4ed5e632">

<img width="1211" alt="Screenshot 2024-06-04 at 6 56 06 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133862121/3a4989d7-58ee-41a9-a997-936b364f6a6e">

**Comment by vaisakhkannan** [comment]
@TrevCraw 
As per changes I did recently , Github action looks like this
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/9956282591

We receive slack notification for build results for every PRs and Lsp4ij main branch 

<img width="1175" alt="Screenshot 2024-07-16 at 6 14 31 PM" src="https://github.com/user-attachments/assets/8e55bec0-2485-467f-a0a8-69703bbfb7b2">

From the above example, we receive two slack notification 

@TrevCraw Do we need another channel for getting build results or just continue to use ` lsp4ij-monitoring`?

**Comment by vaisakhkannan** [comment]
Hi @TrevCraw, 

As per our previous plan to get a single Slack notification for the entire Cron Job build, I have tried and tested it with a single open PR in the lsp4ij repo, and it worked as expected. However, when I checked with multiple open PRs, the results were overwritten each time a PR build was completed. 

The value we get is only the last updated value since we are passing the value from the build.yaml file (a reusable workflow file). Therefore, we don't get all the values corresponding to the build status of each open PR. As a result, we can't confirm the exact result.

Documentation link: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow

For reference : https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10146415319
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/10146431737


I attempted to store values using `artifacts`, but it was not successful. Artifacts can be used to store values from multiple jobs within a single workflow build, but they cannot be used across multiple workflows (e.g., reusable workflows), nor can they be edited or updated across different builds of build.yaml(multiple PRs and multiple LTI tags). As a result, it did not succeed.


@TrevCraw , Can I send the build status to a Slack channel for every build.yaml build?
