### ISSUE TITLE
testInsertJakartaCodeSnippetIntoJavaPart()FAILED due to NoSuchElementException 

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#886]
While running UI tests in windows, GradleSingleModJakartaLSTest > `testInsertJakartaCodeSnippetIntoJavaPart`() is getting failed quite a few times due to ` java.util.NoSuchElementException: List is empty.`. If we re ran the tests a couple of times it is getting success.

Attaching failure logs - https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10064285765/job/27842019395#step:10:836

**Comment by aparnamichael** [comment]
This failure occurs because if we attempt to retrieve snippets before JDK indexing is completed, the Jakarta/MP snippets will not appear in the list. I am able to manually reproduce this issue locally. I think we need to ensure that JDK indexing is finished before starting this test.

https://github.com/user-attachments/assets/d79d3b9d-ac94-4db2-8d4d-e47ae7878233
