### ISSUE TITLE
Start running the cron job in the LTI repo 

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#895]
- [x] Add the necessary Webhook URLs and Secrets to the LTI Repo.
- [x] Remove `lsp4ij-market-0.0.2-integration` from matrix and add existing LTI Tags/Branches before merge to main
- [x] Merge the feature branch into the main
- [x] Verify cron jobs are running from main

**Comment by vaisakhkannan** [comment]
We have added 3 secrets in LTI Repo 

1. SLACK_WEBHOOK_URL

--> This will enable us to receive notifications for `List of LSP4IJ PRs` that currently `opened` and `closed` recently in Slack channel.

2. WORKFLOW_BUILDER_WEBHOOK

--> This will enable us to respond to `LSP4IJ PRs` when `at least one PR` is present to display in slack channel. This PR may come from the `List of Open/New/Updated Pull Requests`, or from the `List of Pull Requests Closed Since the Last Cron Job`, which are identified using a Cron Job.

3. NO_PR_WORKFLOW_BUILDER_WEBHOOK

--> This will enable us to trigger a Slack notification when there are `no PRs to display`. This means both the `List of open/new/updated pull requests` and the `List of pull requests closed since the last cron job` are empty, as identified by a cron job.

**Comment by aparnamichael** [comment]
Completed merging feature branch to main branch and cron job running successfully.
